name: Build and test on jerryhobby.com

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: jerryhobby.com

    steps:
      - uses: actions/checkout@v3
      - name: Create .env files
        run: echo "${{ secrets.ENV_FILE }}" > .env
      - name: Build the application
        run: make build
      - name: Run tests
        run: make test
      - name: Build data engineering
        run: |
         cd src/rust-data-engineering
         make build
      - name: Data engineering tests
        run: make test

